/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload File */
        post: operations["upload_file_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyse/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyse */
        post: operations["analyse_analyse__file_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Results */
        get: operations["get_results_results__file_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** Health Check Head */
        head: operations["health_check_head_health_head"];
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyseRequest */
        AnalyseRequest: {
            /** Analyses */
            analyses?: string[] | null;
            /** Target Column */
            target_column?: string | null;
            /** Classification Target */
            classification_target?: string | null;
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** AnomalyResult */
        AnomalyResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "anomaly";
            /** Anomaly Indices */
            anomaly_indices: number[];
            /** Contamination Rate */
            contamination_rate: number;
            /** Anomaly Rows */
            anomaly_rows: {
                [key: string]: number;
            }[];
            /** Feature Stats */
            feature_stats: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /** Body_upload_file_upload_post */
        Body_upload_file_upload_post: {
            /** File */
            file: string;
        };
        /** ClassificationResult */
        ClassificationResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "classification";
            /** Target Name */
            target_name: string;
            /** Class Labels */
            class_labels: string[];
            /** N Classes */
            n_classes: number;
            /** N Samples */
            n_samples: number;
            /** Cv Folds */
            cv_folds: number;
            /** Cv Accuracy */
            cv_accuracy: number;
            /** Cv Accuracy Std */
            cv_accuracy_std: number;
            /** Baseline Accuracy */
            baseline_accuracy: number;
            /** Macro F1 */
            macro_f1: number;
            /** Confusion Matrix */
            confusion_matrix: number[][];
            /** Feature Names */
            feature_names: string[];
            /** Feature Importances */
            feature_importances: number[];
        };
        /** ClusteringResult */
        ClusteringResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "clustering";
            /** Cluster Labels */
            cluster_labels: number[];
            /** Silhouette Score */
            silhouette_score: number;
            /** N Clusters */
            n_clusters: number;
            /** Feature X */
            feature_x: string;
            /** Feature Y */
            feature_y: string;
            /** X Values */
            x_values: number[];
            /** Y Values */
            y_values: number[];
            /**
             * Pca Projection
             * @default false
             */
            pca_projection: boolean;
        };
        /** ColumnProfile */
        ColumnProfile: {
            /** Missing Count */
            missing_count: number;
            /** Missing Pct */
            missing_pct: number;
            /** Unique Count */
            unique_count: number;
            /** Mean */
            mean?: number | null;
            /** Std */
            std?: number | null;
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Top Values */
            top_values?: components["schemas"]["TopValue"][] | null;
            /** Min Date */
            min_date?: string | null;
            /** Max Date */
            max_date?: string | null;
        };
        /** ColumnSchema */
        ColumnSchema: {
            /** Name */
            name: string;
            column_type: components["schemas"]["ColumnType"];
            profile: components["schemas"]["ColumnProfile"];
        };
        /**
         * ColumnType
         * @enum {string}
         */
        ColumnType: "numeric" | "categorical" | "datetime" | "class_label";
        /** CorrelationPair */
        CorrelationPair: {
            /** Feature A */
            feature_a: string;
            /** Feature B */
            feature_b: string;
            /** R */
            r: number;
        };
        /** CorrelationResult */
        CorrelationResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "correlation";
            /** Columns */
            columns: string[];
            /** Matrix */
            matrix: number[][];
            /** Top Pairs */
            top_pairs: components["schemas"]["CorrelationPair"][];
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RegressionResult */
        RegressionResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "regression";
            /** Coefficients */
            coefficients: number[];
            /** Standardized Coefficients */
            standardized_coefficients: number[];
            /** Feature Names */
            feature_names: string[];
            /** Excluded Columns */
            excluded_columns: string[];
            /** Target Name */
            target_name: string;
            /** R2 Score */
            r2_score: number;
            /** Cv R2 Score */
            cv_r2_score: number | null;
            /** Rmse */
            rmse: number;
            /** N Samples */
            n_samples: number;
            /** Actuals */
            actuals: number[];
            /** Predicted */
            predicted: number[];
        };
        /** ResultsResponse */
        ResultsResponse: {
            /** Results */
            results: {
                [key: string]: components["schemas"]["ClusteringResult"] | components["schemas"]["RegressionResult"] | components["schemas"]["AnomalyResult"] | components["schemas"]["ClassificationResult"] | components["schemas"]["CorrelationResult"];
            };
            /** Summary */
            summary: string;
        };
        /** TopValue */
        TopValue: {
            /** Value */
            value: string;
            /** Count */
            count: number;
        };
        /** UploadResponse */
        UploadResponse: {
            /** File Id */
            file_id: string;
            /** Row Count */
            row_count: number;
            /** Columns */
            columns: components["schemas"]["ColumnSchema"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_file_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyse_analyse__file_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnalyseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_results_results__file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_head_health_head: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
