/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload File */
        post: operations["upload_file_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyse/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyse */
        post: operations["analyse_analyse__file_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Results */
        get: operations["get_results_results__file_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnomalyResult */
        AnomalyResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "anomaly";
            /** Anomaly Indices */
            anomaly_indices: number[];
            /** Contamination Rate */
            contamination_rate: number;
            /** Anomaly Rows */
            anomaly_rows: {
                [key: string]: number;
            }[];
            /** Feature Stats */
            feature_stats: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /** Body_upload_file_upload_post */
        Body_upload_file_upload_post: {
            /** File */
            file: string;
        };
        /** ClusteringResult */
        ClusteringResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "clustering";
            /** Cluster Labels */
            cluster_labels: number[];
            /** Silhouette Score */
            silhouette_score: number;
            /** N Clusters */
            n_clusters: number;
            /** Feature X */
            feature_x: string;
            /** Feature Y */
            feature_y: string;
            /** X Values */
            x_values: number[];
            /** Y Values */
            y_values: number[];
            /**
             * Pca Projection
             * @default false
             */
            pca_projection: boolean;
        };
        /** ColumnSchema */
        ColumnSchema: {
            /** Name */
            name: string;
            column_type: components["schemas"]["ColumnType"];
        };
        /**
         * ColumnType
         * @enum {string}
         */
        ColumnType: "numeric" | "categorical" | "datetime";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RegressionResult */
        RegressionResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "regression";
            /** Coefficients */
            coefficients: number[];
            /** Standardized Coefficients */
            standardized_coefficients: number[];
            /** Feature Names */
            feature_names: string[];
            /** Target Name */
            target_name: string;
            /** R2 Score */
            r2_score: number;
            /** Actuals */
            actuals: number[];
            /** Predicted */
            predicted: number[];
        };
        /** ResultsResponse */
        ResultsResponse: {
            /** Results */
            results: {
                [key: string]: components["schemas"]["ClusteringResult"] | components["schemas"]["RegressionResult"] | components["schemas"]["AnomalyResult"];
            };
            /** Summary */
            summary: string;
        };
        /** UploadResponse */
        UploadResponse: {
            /** File Id */
            file_id: string;
            /** Columns */
            columns: components["schemas"]["ColumnSchema"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_file_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyse_analyse__file_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_results_results__file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
